import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PatientContextProvider } from "@/contexts/patientContext";
import { Logo } from "@/components/logo";
import { Footer } from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PatientContextProvider>
        <body className={inter.className}>
          <nav className="fixed z-50 top-0 px-4 w-full h-14 border-b shadow-sm bg-white flex items-center">
            <Logo />
          </nav>
          <main>{children}</main>
          <Footer />
        </body>
      </PatientContextProvider>
    </html>
  );
}
